---
stages:
  - build-deps
  - esphome-pre-flight
  - device-build

esphome-builder-build:
  stage: build-deps
  tags:
    - home
  script:
    - aws s3 cp s3://${SECRETS_BUCKET}/esphome-secrets.yaml devops/esphome-builder/secrets.yaml
    - cp *.yaml devops/esphome-builder
    - docker build -t esphome-builder devops/esphome-builder
#check:
#  stage: esphome-pre-flight
#  before_script:
#    - sh devops/esphome_wrapper.sh dummy.yaml version
#  script:
#    - |
#     for file in $(find \
#        ./esphome \
#        -type f \
#        -name "*.yaml"\
#        -not -name "secrets.yaml"
#        ); do
#        sh devops/esphome_wrapper.sh $(basename $file) config
#      done
#  tags:
#    - home
#  only:
#      refs:
#        - master
#      changes:
#        - esphome/*.yaml

.device-build: &device-build
  stage: device-build
  tags:
    - home

3d_printer_lights_switch:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh 3d_printer_lights_switch.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - 3d_printer_lights_switch.yaml

office_temp_sensor:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh temp-sensor-office.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - temp-sensor-office.yaml

shop_lights_switch:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh shop_lights_switch.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - shop_lights_switch.yaml

wordclock:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh wordclock.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - wordclock.yaml

dryer:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh dryer.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - dryer.yaml
office_light_switch:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh office_light_switch.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - office_light_switch.yaml
floor_lamp_switch:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh floor_lamp_switch.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - floor_lamp_switch.yaml
