---
stages:
  - build-deps
  - services-build
  - services-deploy
  - esphome-pre-flight
  - device-build

esphome-builder-build:
  stage: build-deps
  tags:
    - home
  script:
    - aws s3 cp s3://${SECRETS_BUCKET}/esphome-secrets.yaml devops/esphome-builder/secrets.yaml
    - cp esphome/*.yaml devops/esphome-builder
    - docker build -t esphome-builder devops/esphome-builder
  only:
      refs:
        - master
      changes:
        - esphome/*.yaml
#check:
#  stage: esphome-pre-flight
#  before_script:
#    - sh devops/esphome_wrapper.sh dummy.yaml version
#  script:
#    - |
#     for file in $(find \
#        ./esphome \
#        -type f \
#        -name "*.yaml"\
#        -not -name "secrets.yaml"
#        ); do
#        sh devops/esphome_wrapper.sh $(basename $file) config
#      done
#  tags:
#    - home
#  only:
#      refs:
#        - master
#      changes:
#        - esphome/*.yaml

.device-build: &device-build
  stage: device-build
  tags:
    - home

3d_printer_lights_switch:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh 3d_printer_lights_switch.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - esphome/3d_printer_lights_switch.yaml

office_temp_sensor:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh temp-sensor-office.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - esphome/temp-sensor-office.yaml

shop_lights_switch:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh shop_lights_switch.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - esphome/shop_lights_switch.yaml

wordclock:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh wordclock.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - esphome/wordclock.yaml

dryer:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh dryer.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - esphome/dryer.yaml

homeassistant-build:
  stage: services-build
  tags:
    - home
  script:
    - aws s3 cp s3://${SECRETS_BUCKET}/hass-secrets.yaml hass/secrets.yaml
    - aws s3 cp s3://${SECRETS_BUCKET}/secrets.env secrets.env
    - aws s3 cp hass "s3://${PERSIST_BUCKET}/" --recursive
    - docker-compose build homeassistant
  only:
    refs:
      - master
    changes:
      - hass/*

esphome-build:
  stage: services-build
  tags:
    - home
  script:
    - aws s3 cp s3://${SECRETS_BUCKET}/secrets.env secrets.env
    - aws s3 cp s3://${SECRETS_BUCKET}/esphome-secrets.yaml esphome/secrets.yaml
    - docker-compose build esphome
  only:
    refs:
      - master
    changes:
      - esphome/*

esphome-deploy:
  stage: services-deploy
  tags:
    - home
  script:
    - aws s3 cp s3://${SECRETS_BUCKET}/secrets.env secrets.env
    - docker-compose up -d esphome
  dependencies:
    - homeassistant-build

homeassistant-deploy:
  stage: services-deploy
  tags:
    - home
  script:
    - aws s3 cp s3://${SECRETS_BUCKET}/secrets.env secrets.env
    - docker-compose up -d homeassistant
  dependencies:
    - homeassistant-build
