---
stages:
  - build-deps
  - services-build
  - services-deploy
  - esphome-pre-flight
  - device-build

esphome-builder-build:
  stage: build-deps
  tags:
    - home
  script:
    - aws s3 cp s3://${S3_BUCKET_NAME}/esphome-secrets.yaml devops/esphome-builder/secrets.yaml
    - cp esphome/*.yaml devops/esphome-builder
    - docker build -t esphome-builder devops/esphome-builder

check:
  stage: esphome-pre-flight
  before_script:
    - sh devops/esphome_wrapper.sh dummy.yaml version
  script:
    - |
      for file in $(find \
        ./esphome \
        -type f \
        -name "*.yaml"\
        -not -name "secrets.yaml"
        ); do
        sh devops/esphome_wrapper.sh $(basename $file) config
      done
  tags:
    - home

.device-build: &device-build
  stage: device-build
  tags:
    - home

3d_printer_lights_switch:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh 3d_printer_lights_switch.yaml run --no-logs


office_temp_sensor:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh temp-sensor-office.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - esphome/temp-sensor-office.yaml

shop_lights_switch:
  <<: *device-build
  script:
    - sh devops/esphome_wrapper.sh shop_lights_switch.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - esphome/shop_lights_switch.yaml


homeassistant-build:
  stage: services-build
  tags:
    - home
  script:
    - aws s3 cp s3://${S3_BUCKET_NAME}/hass-secrets.yaml hass/secrets.yaml
    - docker-compose build homeassistant

homeassistant-deploy:
  stage: services-deploy
  tags:
    - home
  script:
    - docker-compose up -d homeassistant
