stages:
  - build-deps
  - pre-flight
  - device-build
esphome-builder:
  stage: build-deps
  tags:
    - home
  script:
    - cp esphome/*.yaml devops/esphome-builder
    - docker build -t esphome-builder devops/esphome-builder

check:
  stage: pre-flight
  before_script:
    - docker run -t --rm esphome-builder dummy.yaml version
  script:
    - |
      for file in $(find \
        ./esphome \
        -type f \
        -name "*.yaml"\
        -not -name "secrets.yaml"
        ); do
        docker run -t --rm esphome-builder $(basename $file) config
      done
  tags:
    - home

office_temp_sensor:
  stage: device-build
  tags:
    - home
  script:
    - docker run -t --rm esphome-builder temp-sensor-office.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - esphome/temp-sensor-office.yaml
