esphome:
  name: compressor_valve
  platform: ESP8266
  board: d1_mini

switch:
  - platform: template
    name: "Valve"
    id: servo_switch
    turn_on_action:
      - servo.write:
          id: my_servo
          level: 0.5
      - delay: 2s
      - servo.detach: my_servo
    turn_off_action:
      - servo.write:
          id: my_servo
          level: 0
      - delay: 2s
      - servo.detach: my_servo
    optimistic: true

servo:
  - id: my_servo
    output: pwm_output

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Button"
    on_press:
      then:
        - switch.toggle: servo_switch
# Example output platform
# On ESP32, use ledc output
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D4
    frequency: 50 Hz

# Sun Mar  1 17:05:41 CST 2020
<<: !include secrets.yaml
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}

# Enable Home Assistant API
api:

ota:

logger:
