esphome:
  name: compressor_power
  platform: ESP8266
  board: esp01_1m

switch:
  - platform: gpio
    name: "Power"
    id: power_switch
    pin: GPIO12

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Button"
    on_press:
      then:
        - switch.toggle: power_switch

<<: !include secrets.yaml
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  use_address: compressor.local
# Enable Home Assistant API
api:

ota:

logger:
