esphome:
  name: compressor
  platform: ESP8266
  board: esp01_1m

switch:
  - platform: template
    name: "Switch"
    id: servo_switch
    turn_on_action:
      - servo.write:
          id: my_servo
          level: 0.7
      - delay: 2s
      - servo.detach: my_servo
    turn_off_action:
      - servo.write:
          id: my_servo
          level: -1.0
      - delay: 2s
      - servo.detach: my_servo
    optimistic: true

servo:
  - id: my_servo
    output: pwm_output

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Button"
    on_press:
      then:
        - switch.toggle: servo_switch
# Example output platform
# On ESP32, use ledc output
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO1
    frequency: 50 Hz

logger:
  baud_rate: 0

# Sun Mar  1 17:05:41 CST 2020
<<: !include secrets.yaml
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  use_address: floor_lamp_switch.local

# Enable Home Assistant API
api:

ota:

