esphome:
  name: garage_door_switch
  platform: ESP8266
  board: nodemcuv2

<<: !include common.yaml

switch:
  - platform: gpio
    pin: D6
    id: relay
    inverted: yes
  - platform: template
    name: "Garage Door Opener"
    icon: "mdi:garage"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay# Sun Mar  1 17:05:41 CST 2020
