esphome:
  name: temp_sensor_office
  platform: ESP8266
  board: d1_mini
<<: !include common.yaml

i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  
sensor:
  - platform: bmp280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    
    address: 0x76
    update_interval: 4s


