---
homeassistant:
  name: Home
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

config:
updater:
#discovery:
history:
logbook:
map:
sun:
cloud:
tts:
  platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
light: !include lights.yaml
sensor: !include sensors.yaml

#octoprint:
#  host: 192.168.1.107
#  api_key: !secret octoprint_api_key
#  name: Prusa MK3S
#  port: 5000
#  bed: true
#  number_of_tools: 1

zone:
  - name: UT
    latitude: 30.28554
    longitude: -97.7395817
    radius: 1000
    icon: mdi:school
  - name: General Motors
    latitude: 30.413004
    longitude: -97.6624797
    radius: 500
  - name: Home
    latitude: 30.357821
    longitude: -97.729185
    radius: 200

mqtt:
  broker: micahf.com
  port: 1883
#  discovery: true
#  discovery_prefix: homeassistant
device_tracker:
  - platform: mqtt_json
    devices:
      micahs_phone: location/micah
  - platform: automatic
    client_id: !secret automatic_client_id
    secret: !secret automatic_client_secret


notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

counter:
  litter_box_visits:
    initial: 0
    step: 1
  cheddar_feedings:
    initial: 0
    step: 1
hacs:
  token: !secret hacs_token

frontend:
  !include themes.yaml
#recorder:
#  db_url: !secret postgres_url
#  purge_keep_days: 90
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.1.107:8090?action=snapshot
    mjpeg_url: http://192.168.1.107?action=stream

binary_sensor:
  - platform: threshold
    entity_id: sensor.tv_power
    upper: 2
    name: tv_state
  - platform: threshold
    entity_id: sensor.dryer_current
    upper: 0.5
    name: Dryer
  - platform: threshold
    entity_id: sensor.stereo_power
    upper: 2
    name: stereo_state
  - platform: wyzesense
    device: "/dev/hidraw0"
  - platform: workday
    country: US

climate:
  - platform: honeywell
    username: mcfitz2@gmail.com
    password: !secret honeywell_pass
    region: us

cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage Door"
        position_template: >-
          {% if is_state("binary_sensor.garage_door_open", "off") -%}
          100
          {%- elif is_state("binary_sensor.garage_door_closed", "off") -%}
          0
          {%- elif is_state("binary_sensor.garage_door_closed", "on") and is_state("binary_sensor.garage_door_open", "on") -%}
          50
          {%- endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door_opener
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door_opener
        stop_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door_opener



input_boolean:
  tv_assumed_state:
    name: TV Assumed State
    initial: off
weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily
