---
- platform: mqtt
  name: "Kenwood_IR"
  command_topic: "mqtt-lirc/Kenwood/KEY_POWER"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "TV_IR"
  command_topic: "mqtt-lirc/insignia/KEY_POWER"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Xbox_IR"
  command_topic: "mqtt-lirc/Microsoft_Xbox360/KEY_POWER"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: template
  switches:
    tv:
      friendly_name: TV
      value_template: "{{ is_state('binary_sensor.tv_state', 'on') or is_state('input_boolean.tv_assumed_state', 'on')}}"
      turn_on:
        service: script.tv_start
      turn_off:
        service: script.tv_stop
    stereo:
      friendly_name: Stereo
      value_template: "{{ is_state('binary_sensor.stereo_state', 'on') }}"
      turn_on:
        service: script.stereo_start
      turn_off:
        service: script.stereo_stop


