accessControl:
  salt: eIQk8buJdNI8QeDHyseMy819uhhs8xV2
api:
  allowCrossOrigin: true
  key: 6110A9B9D7034C6B9CB1EC041C4BBAE0
appearance:
  color: blue
  name: Maker Select
controls:
- children:
  - commands:
    - M104 S195
    - M140 S65
    - M106 S255
    name: Preheat
    type: command
  - commands:
    - M104 S0
    - M140 S0
    - M107
    name: Turn Off Extruder/Bed
    type: command
  - commands:
    - M80
    name: Power On
    type: command
  - commands:
    - M81
    name: Power Off
    type: command
  name: Custom
  type: section
devel:
  virtualPrinter:
    enabled: true
events:
  enabled: true
  subscriptions:
  - command: curl "http://192.168.1.17/cm?cmnd=Power%20On"
    event: PowerOn
    type: system
  - command: curl "http://192.168.1.17/cm?cmnd=Power%20Off"
    event: PowerOff
    type: system
feature:
  keyboardControl: false
  modelSizeDetection: false
  temperatureGraph: false
gcodeViewer: {}
plugins:
  _disabled:
  - cura
  - displayz
  - touchui
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1582800000
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1573722900
      _plugins:
        read_until: 1517270400
      _releases:
        read_until: 1582726200
    enabled_channels:
    - _octopi
    - _important
    - _releases
    - _blog
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
    upnpUuid: e6994525-c7da-4d03-8b53-d3af40ccc514
  emailnotifier:
    _config_version: 1
  firmwareupdater:
    avrdude_path: /usr/bin/avrdude
  mqtt:
    broker:
      url: mqtt
    publish:
      printerData: true
  mqttpublish:
    _config_version: 1
  softwareupdate:
    _config_version: 6
    check_providers:
      bedlevelvisualizer: bedlevelvisualizer
      detailedprogress: detailedprogress
      displayprogress: displayprogress
      eeprom_repetier: eeprom_repetier
      emailnotifier: emailnotifier
      firmwareupdater: firmwareupdater
      growl: growl
      m73etaoverride: m73etaoverride
      mqtt: mqtt
      mqttpublish: mqttpublish
      printhistory: printhistory
      systemcommandeditor: eeprom_MPSelectMini
      touchui: touchui
      yamlpatcher: yamlpatcher
    checks:
      octoprint:
        checkout_folder: /home/pi/OctoPrint
        update_script: '{python} "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.2-py2.7.egg/octoprint/plugins/softwareupdate/scripts/update-octoprint.py"
          --python="{python}" "{folder}" {target}'
  touchui:
    hasCustom: false
    refreshCSS: false
    requireNewCSS: false
    whatsNew: false
printerParameters: {}
printerProfiles:
  default: _default
  defaultProfile:
    axes:
      e:
        inverted: false
        speed: 300
      x:
        inverted: false
        speed: 6000
      y:
        inverted: false
        speed: 6000
      z:
        inverted: false
        speed: 200
    color: blue
    extruder:
      count: 1
      nozzleDiameter: 0.4
      offsets:
      - - 0.0
        - 0.0
    heatedBed: true
    id: _default
    model: DBot
    name: DBot
    volume:
      depth: 200.0
      formFactor: rectangular
      height: 200.0
      origin: lowerleft
      width: 200.0
serial:
  baudrate: 115200
  externalHeatupDetection: false
  port: /dev/ttyACM0
  timeout:
    communication: 60.0
  waitForStartOnConnect: true
server:
  commands:
    serverRestartCommand: service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: SkNBP0OemxwirfyF8aaQbNi7ldcSisMi
  seenWizards:
    bedlevelvisualizer: null
    corewizard: 3
system:
  actions:
  - action: poweron
    command: curl "http://192.168.1.17/cm?cmnd=Power%20On"
    name: Power On
  - action: poweroff
    command: curl "http://192.168.1.17/cm?cmnd=Power%20Off"
    confirm: You are about to power off the 3D printer
    name: Power Off
temperature:
  profiles:
  - bed: 100
    extruder: 245
    name: ABS
  - bed: 70
    extruder: 200
    name: PLA
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://localhost:8080/?action=snapshot
  stream: http://192.168.1.107:8090/?action=stream
  streamRatio: '4:3'
  timelapse:
    fps: 25
    options: {}
    postRoll: 0
    type: 'off'
