<<: !include secrets.yaml
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:


sensor:
  - platform: adc
    pin: VCC
    name: "Battery Voltage"