esphome:
  name: floor_lamp_switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "NETGEAR10"
  password: "fancyunicorn486"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "floor_lamp_power"
    pin: GPIO12
