esphome:
  name: temp_sensor_office
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "NETGEAR10"
  password: "fancyunicorn486"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  
sensor:
  - platform: bmp280
    temperature:
      name: "Office Temperature2"
      oversampling: 16x
    pressure:
      name: "Office Pressure"
    
    address: 0x76
    update_interval: 3s


